server:
  port: 31500

spring:

  application:
    name: dashboard

cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde

      bindings:

        visits-before-aggregation:
          destination: visits-for-statistics-ks
          consumer:
            header-mode: raw
#          content-type: application/json
#          consumer.use-native-decoding: true
#          consumer.key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#          producer.key-serde: org.apache.kafka.common.serialization.Serdes$ByteArraySerde
#          consumer.value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde

#        visits-after-aggregation:
#          destination: visits-after-aggregation
#          producer.use-native-encoding: true
#          producer.key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
##          producer.key-serde: org.apache.kafka.common.serialization.Serdes$ByteArraySerde
#          producer.value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde

