server:
  port: 31500

spring:
  application:
    name: dashboard

  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              commit:
                interval:
                  ms: 1000

      bindings:
        visits-before-aggregation:
          destination: visits-for-statistics-ks
          consumer:
            header-mode: raw

