spring:
  cloud:
    stream:
      bindings:

        visits-after-aggregation:
          destination: visits-after-aggregation

        visits-before-aggregation:
          destination: visits-before-aggregation

  }